(defmode MODE-PRIMSUBS-DISPLAY2
 (FLAG-SETTINGS (PRIMSUB-VAR-SELECT T) (PRIMSUB-METHOD PR95) (PRIM-QUANTIFIER T) (PRIM-PREFIX PRIM) (PRIM-BDTYPES-AUTO REPLACE) (PRIM-BDTYPES ("A")) (NEG-PRIM-SUB NIL) (MS91-INTERLEAVE 5) (MIN-PRIM-LITS 2) (MIN-PRIM-DEPTH 1) (MAX-PRIM-LITS 1) (MAX-PRIM-DEPTH 1))
 (mhelp "mode for displaying primsubs for THM104 with projection"))
