(defmode MODE-THM129-B
 (FLAG-SETTINGS (SEARCH-TIME-LIMIT 60) (ORDER-COMPONENTS T) (MAX-SEARCH-LIMIT NIL) (INITIAL-BKTRACK-LIMIT 1000000) (UNIFY-VERBOSE T) (ETA-RULE T) (IMITATION-FIRST T) (MAX-SEARCH-DEPTH 8) (MAX-UTREE-DEPTH 8) (MIN-QUICK-DEPTH 3) (REDUCE-DOUBLE-NEG T) (STOP-AT-TSN T) (SUBSUMPTION-CHECK NIL) (APPLY-MATCH APPLY-MATCH-ALL-FRDPAIRS) (UNI-SEARCH-HEURISTIC BREADTH-FIRST) (DEFAULT-MS MS88))
 (mhelp "Once the right primsub is made, MS88 quickly 
finds the proof using these unification settings. 
Use with MS89, not MS88, to prove the full theorem."))
