(defmode MODE-PRIMSUBS-DISPLAY
 (FLAG-SETTINGS (PRIMSUB-VAR-SELECT NIL) (PRIMSUB-METHOD PR95) (PRIM-QUANTIFIER T) (PRIM-PREFIX PRIM) (PRIM-BDTYPES-AUTO IGNORE) (PRIM-BDTYPES ("B" "OB")) (NEG-PRIM-SUB T) (MS91-INTERLEAVE 5) (MIN-PRIM-LITS 2) (MIN-PRIM-DEPTH 1) (MAX-PRIM-LITS 2) (MAX-PRIM-DEPTH 2))
 (mhelp "primsub flags for displaying primsubs in papers"))
