(defmode MODE-THM178-A
 (FLAG-SETTINGS (SEARCH-TIME-LIMIT 30) (NUM-OF-DUPS 0) (MIN-PRIM-DEPTH 1) (MAX-SUBSTS-VAR 3) (MAX-SUBSTS-QUICK 6) (MAX-SEARCH-LIMIT NIL) (MAX-PRIM-DEPTH 1) (MAX-MATES 1) (DEFAULT-MS MS91-6))
 (mhelp "Mode for THM178 found quickly by using UNIFORM-SEARCH."))
