(defmode MS90-9-FLAGS
 (FLAG-SETTINGS (RECORDFLAGS (LAST-MODE-NAME DEFAULT-MS SHORT-SITE-NAME MACHINE-TYPE LISP-IMPLEMENTATION-TYPE MAX-SEARCH-LIMIT SEARCH-TIME-LIMIT MAX-SEARCH-DEPTH NUM-FRPAIRS FIRST-ORDER-MODE-MS NUM-OF-DUPS MAX-MATES ORDER-COMPONENTS REWRITE-DEFNS REWRITE-EQUALITIES REMOVE-LEIBNIZ ORDER-COMPONENTS NEG-PRIM-SUB PRIM-QUANTIFIER OCCURS-CHECK RANK-EPROOF-FN SKOLEM-DEFAULT MIN-QUANTIFIER-SCOPE)) (PRINT-MATING-COUNTER 300000) (SHOW-TIME T) (MAX-SEARCH-DEPTH 20) (MAX-SEARCH-LIMIT NIL) (SEARCH-TIME-LIMIT 60) (DEFAULT-MS MS90-9))
 (mhelp "Flags for MS90-9"))
