(defmode TEST1MODE
 (FLAG-SETTINGS (PRIMSUB-VAR-SELECT T) (PRIMSUB-METHOD PR93) (PRIM-QUANTIFIER T) (PRIM-PREFIX PRIM) (PRIM-BDTYPES-AUTO REPLACE) (PRIM-BDTYPES (I)) (PR97C-PRENEX T) (PR97C-MAX-ABBREVS 1) (NEG-PRIM-SUB NIL) (MS91-INTERLEAVE 5) (MIN-PRIM-LITS 2) (MIN-PRIM-DEPTH 1) (MAX-PRIM-LITS 4) (MAX-PRIM-DEPTH 1))
 (mhelp "testtt"))
