(defmode TRIV0TESTMODE
 (FLAG-SETTINGS (TOTAL-NUM-OF-DUPS NIL) (SEARCH-TIME-LIMIT 60) (REWRITE-EQUIVS 1) (REWRITE-EQUALITIES ALL) (REWRITE-DEFNS (LAZY1)) (PRIMSUB-METHOD PR93) (PRIM-BDTYPES-AUTO REPLACE) (PRIM-BDTYPES ("I")) (PR97C-PRENEX T) (PR97C-MAX-ABBREVS 1) (ORDER-COMPONENTS T) (NUM-OF-DUPS 1) (MIN-PRIM-LITS 2) (MIN-PRIM-DEPTH 1) (MAX-UTREE-DEPTH 10) (MAX-SUBSTS-VAR NIL) (MAX-SUBSTS-QUICK NIL) (MAX-SEARCH-LIMIT NIL) (MAX-SEARCH-DEPTH 18) (MAX-PRIM-LITS 4) (MAX-PRIM-DEPTH 1) (MAX-MATES 3) (DEFAULT-MS MS90-3))
 (mhelp ""))
